version: '3.8'
services:
  mysql:
    build: ./mysql/
    tty: true
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/ddl/:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      TZ: ${TZ}
volumes:
  mysql-data: